working_dir:  # absolute path to working directory. path must end with '/'
raw_file_extension: # fastq.gz, fq.gz, FASTQ.gz, FQ.gz, etc. (must start AFTER the first '.') Note: this pipelines assumes raw files are gzipped fastq files!
read_length: # read length
TEtrx_strandedness: # 'no', 'forward', or 'reverse'
Tel_strandedness: # 'None', 'FR', or 'RF'
Picard_strandedness: # 'NONE', 'FIRST_READ_TRANSCRIPTION_STRAND', 'SECOND_READ_TRANSCRIPTION_STRAND' (for CollectRnaSeqMetrics)
STAR_genomeDir: "/SMHS/groups/chiappinellilab/genomes/hg38/STAR.hg38.index.2.7.0e.100.v.21" # --genomeDir option in STAR command. Make sure this matches the read length
STAR_GTF: "/SMHS/groups/chiappinellilab/genomes/hg38/gencode.annotation/gencode.v21.primary.assembly.only.annotation.gtf" # --sjdbGTFfile option in STAR command
REF_FLAT: "/SMHS/groups/chiappinellilab/genomes/hg38/gencode.annotation/gencode.v21.refFlat.txt" # Path to refFlat file for Picard's CollectRnaSeqMetrics
rRNA_interval_list: "/SMHS/groups/chiappinellilab/genomes/hg38/rRNA/gencode.v21.rRNA.interval_list" # Path to rRNA interval list for Picard's CollectRnaSeqMetrics
TEtrx_TE: "/SMHS/groups/chiappinellilab/genomes/hg38/RepeatMasker/hg38_rmsk_TE.gtf" # --TE option in TEtranscripts command (RE annotation file path)
Telescope_GTF: "/SMHS/groups/chiappinellilab/genomes/hg38/HERV_L1_rmsk.hg38.gtf" # telescope annotation file path
TEloc_TE: "/SMHS/groups/chiappinellilab/genomes/hg38/RepeatMasker/rmsk_hg38_TE_local.locInd"
envs:
  fastqc: "envs/fastqc.yaml"
  trimgalore: "envs/trimGalore.yaml"
  picard: "envs/picard.yaml"
  telescope: "envs/telescope.yaml"
  tetranscripts: "envs/tetranscripts.yaml"
  telocal: "envs/telocal.yaml"
  combine_counts: "envs/combine_counts.yaml"